# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 02:03
from __future__ import unicode_literals

from django.db import migrations
import wham.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', wham.fields.WhamCharField(max_length=255, primary_key=True, serialize=False)),
                ('name', wham.fields.WhamCharField(max_length=255)),
                ('full_name', wham.fields.WhamTextField()),
                ('html_url', wham.fields.WhamURLField()),
                ('description', wham.fields.WhamTextField(null=True)),
                ('url', wham.fields.WhamURLField()),
                ('stargazers_count', wham.fields.WhamIntegerField()),
                ('watchers_count', wham.fields.WhamIntegerField()),
                ('forks_count', wham.fields.WhamIntegerField()),
                ('open_issues_count', wham.fields.WhamIntegerField()),
                ('has_issues', wham.fields.WhamBooleanField()),
                ('language', wham.fields.WhamCharField(max_length=255, null=True)),
                ('created_at', wham.fields.WhamDateTimeField()),
                ('updated_at', wham.fields.WhamDateTimeField()),
                ('pushed_at', wham.fields.WhamDateTimeField()),
                ('size', wham.fields.WhamIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
